# Generated by Django 4.2.7 on 2023-11-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_author',
            field=models.BooleanField(default=True),
        ),
    ]
