# Generated by Django 4.2.7 on 2023-11-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
