# Generated by Django 4.2.7 on 2023-11-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_image/%Y/'),
        ),
    ]
