# Generated by Django 4.2.7 on 2023-11-20 08:19

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userinfo_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
