# Generated by Django 4.2.7 on 2023-11-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aboutcategory_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
