# Generated by Django 4.2.7 on 2023-11-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_hit_post_hits'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hit',
            unique_together={('ip', 'post')},
        ),
    ]
